### ISSUE TITLE
Not pulling on all machines

### ISSUE THREAD

**Issue by infineonnetworks** [ryanblenis/MeshCentral-EventLog#1]
After playing with this plugin for a few days now, I have noticed that while it pulls the system and application logs on ~80% of the systems, there are some that it just won't pull the logs from and thus the plugins section remains blank. Even issuing the manual plugin eventlog pull command doesn't seem to do anything. 

- Windows 10 systems ~90% successful, the 10% suspecting it may have something to do with Antivirus/Firewalls (AV provider FW's).

- Windows 2016 - 100% successful. 
- Windows 2012 R2 ~95% successful.

- Windows 2008r2 0% successful, it may have something to do with how logs are accessed on older systems. 

If there are any logs specifically we need to collect to help debug this please let us know.

**Comment by ryanblenis** [comment]
Thanks for the report! Glad to see someone's trying it out!

The plugin relies on the Get-WinEvent Powershell command currently (which I believe was introduced back in Powershell v3). If you haven't updated on your older machines (such as the 2008R2- then this would be the reason why. Can you confirm this with the 2008R2 machines?

As for the other 90+% machines- do they not report anything back at all for the machine (live and/or history)? Does history come in sometimes and not others?

Also, when you say the plugin section remains blank, is the header for Event Log there, or does that disappear as well?

A debug flag is coming soon. I've made several changes for an upcoming version, but the release will likely be timed around when Ylian (from the MeshCentral project) gets back from his travels, as I'm trying to integrate a GUI to interface with plugins via MeshCentral to offer more choices.

**Comment by infineonnetworks** [comment]
You would guess it has to do a lot with the PowerShell version. 2008R2 were only shipped with Powershell V2.  I will see if I can upgrade it to 3 or even 4, but we will see the outcome.

**Comment by ryanblenis** [comment]
The 2012R2's and Win10 machines may be the same problem. Interested to see what you find!

**Comment by ryanblenis** [comment]
Just wanted to check in on your findings here, otherwise I'll close this out in a couple days and assume it was the Powershell versions causing the issue. Thank you.
