### ISSUE TITLE
Security rights for plugins

### ISSUE THREAD

**Issue by MordyT** [ryanblenis/MeshCentral-EventLog#3]
I'm unsure if it's there and I am missing something, but I can't find a way to restrict being able to access this plugin by user.

For all users I can edit restrictions and server rights to prevent anything from router access to adding new devices and more. But no where do I see a way to stop them from getting event logs (as an example).

**Comment by ryanblenis** [comment]
Hi @MordyT,

I haven't yet added any fine-grained permissions to the plugin. It is currently either "enabled" or "disabled". In terms of a feature request, what are you looking to enable/restrict per user? Access to the plugin in general? Configuration sets per user? Etc. Thank you for your input.

**Comment by ryanblenis** [comment]
Closing this as non-responsive. If anyone has any input on how permissions should be implemented, whether on a plugin basis, or a more central control baked directly into MeshCentral I'm open to hearing about them and working on it. Thank you.
